import { CirclePlus } from 'lucide-react';
export const BusinessModalFormConfig = {
    moduleTitle: 'Manage Business',
    title: 'Create Business',
    description: 'Fill in the details below to create a new business!',
    addButton: {
        id: 'add-business',
        label: 'Add Business',
        className: 'cursor-pointer rounded-lg bg-sky-500 px-4 py-2 text-white hover:bg-sky-600',
        icon: CirclePlus,
        type: 'button',
        variant: 'default',
    },
    fields: [
        {
            id: 'business-name',
            key: 'name',
            name: 'name',
            label: 'Business Name',
            type: 'text',
            placeholder: 'Enter business name',
            autocomplete: 'name',
            tabIndex: 1,
            autoFocus: true,
        },
        {
            id: 'business-description',
            key: 'description',
            name: 'description',
            label: 'Description',
            type: 'textarea',
            placeholder: 'Enter business description',
            autocomplete: 'description',
            tabIndex: 2,
            rows: 3,
            className: 'rounded border p-2 w-full',
        },
        {
            id: 'business-image',
            key: 'image',
            name: 'image',
            label: 'Image (optional)',
            type: 'file',
            accept: 'image/*',
            tabIndex: 3,
        },
        {
            id: 'type',
            key: 'type',
            name: 'type',
            label: 'Type of business',
            type: 'single-select',
            tabIndex: 4,
            options: [
                { label: 'Shop', value: 'shop', key: 'shop' },
                { label: 'Service', value: 'service', key: 'service' },
                { label: 'Cafe', value: 'cafe', key: 'cafe' },
                { label: 'Other', value: 'other', key: 'other' },
            ],
        },
    ],
    buttons: [
        {
            key: 'cancel',
            type: 'button',
            label: 'Cancel',
            variant: 'ghost',
            className: 'cursor-pointer',
        },
        {
            key: 'submit',
            type: 'submit',
            label: 'Save',
            variant: 'default',
            className: 'cursor-pointer',
        },
    ],
};

export const BusinessModalFormRequest = {
    moduleTitle: 'Manage Request',
    title: 'Create Request',
    description: 'Fill in the details below to create a new request!',
    fields: [
        {
            id: 'request-name',
            key: 'name',
            name: 'request_name',
            label: 'Request Name',
            type: 'text',
            placeholder: 'Enter request name',
            autocomplete: 'name',
            tabIndex: 1,
            autoFocus: true,
        },
        {
            id: 'request-phone',
            key: 'phone',
            name: 'phone',
            label: 'Request Phone',
            type: 'text',
            placeholder: 'Enter request phone',
            autocomplete: 'phone',
            tabIndex: 2,
            autoFocus: true,
        },
        {
            id: 'date',
            key: 'date',
            name: 'date',
            label: 'Chose date for request',
            type: 'date-select',
            tabIndex: 3,
        },
        {
            id: 'request-description',
            key: 'description',
            name: 'request_description',
            label: 'Description',
            type: 'textarea',
            placeholder: 'Enter request description',
            autocomplete: 'description',
            tabIndex: 4,
            rows: 3,
            className: 'rounded border p-2 w-full',
        },
    ],
};
