import {CirclePlus} from 'lucide-react';

export const ConfigModalFormAnime = {
    moduleTitle: 'Manage Anime',
    title: 'Create Anime',
    description: 'Fill in the details below to create a new anime!',
    addButton: {
        id: 'add-anime',
        label: 'Add Anime',
        className: 'cursor-pointer rounded-lg bg-indigo-500 px-4 py-2 text-white hover:bg-indigo-600',
        icon: CirclePlus,
        type: 'button',
        variant: 'default',
    },
    fields: [
        {
            id: 'anime name',
            key: 'name',
            name: 'name',
            label: 'Anime Title',
            type: 'text',
            placeholder: 'Enter title here',
            autocomplete: 'name',
            tabIndex: 1,
            autoFocus: true,
        },
        {
            id: 'anime-description',
            key: 'description',
            name: 'description',
            label: 'Description',
            type: 'textarea',
            placeholder: 'Enter anime description',
            autocomplete: 'description',
            tabIndex: 2,
            rows: 3,
            className: 'rounded border p-2 w-full',
        },
        {
            id: 'anime rate',
            key: 'rate',
            name: 'rating',
            label: 'Anime Rating',
            type: 'text',
            placeholder: 'Enter rate here',
            autocomplete: 'rate',
            tabIndex: 3,
            autoFocus: true,
        },
        {
            id: 'featured_image',
            key: 'featured_image',
            name: 'featured_image',
            label: 'Featured Image',
            type: 'file',
            accept: 'image/*',
            tabIndex: 4,
        },
        {
            id: 'anime files',
            key: 'files',
            name: 'files',
            label: 'Anime Files',
            type: 'files',
            autocomplete: 'rate',
            tabIndex: 5,
        },
    ],
    buttons: [
        {
            key: "cancel",
            type: 'button',
            label: 'Cancel',
            variant: 'ghost',
            className: 'cursor-pointer',
        },
        {
            key: "submit",
            type: "submit",
            label: "Save Category",
            variant: "default",
            className: "cursor-pointer",
        }
    ],
}
